services:
  redis:
    image: redis:latest
    command: redis-server
    expose:
      - 6379
    ports:
      - "6379:6379"

  postgres:
    image: postgres:latest
    networks:
      - my_network
    environment:
      POSTGRES_DB: reopt
      POSTGRES_USER: reopt_api
      POSTGRES_PASSWORD: reopt
    expose:
      - 5432

  celery:
    build:
      context: .
      dockerfile: Dockerfile
    image: base-api-image
    command: celery -A reopt_api worker --loglevel=info
    # command: sh -c "celery -A reopt_api worker --loglevel=info"
    environment:
      - APP_ENV=local
      - DJANGO_SETTINGS_MODULE=reopt_api.dev_settings  # Ensure this matches your settings file
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - REDIS_HOST=redis
    volumes:
      - .:/opt/reopt
    depends_on:
      - postgres
      - redis
    networks:
      - my_network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
        labels: "celery"
    env_file:
      - .env  # If you're using an environment file

  django:
    build:
      context: .
      dockerfile: Dockerfile
    image: base-api-image
    # command: bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    #command: python manage.py runserver 0.0.0.0:8000
    # command: bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000 > /opt/reopt/django.log 2>&1"
    # command: ["/bin/bash", "-c", "/opt/reopt/start_django.sh"]
    command: ["/bin/bash", "/opt/reopt/start_django.sh"]
    volumes:
      - ./start_django.sh:/opt/reopt/start_django.sh
      - .:/opt/reopt
    tty: true
    stdin_open: true
    environment:
      - APP_ENV=local
      - SQL_HOST=postgres
      - SQL_PORT=5432
      - REDIS_HOST=redis
      - DATABASE_URL=postgres://reopt_api:reopt@postgres:5432/reopt
      - DJANGO_SETTINGS_MODULE=reopt_api.dev_settings
    depends_on:
      - postgres
      - redis
      - julia
    ports:
      - 8000:8000
    networks:
      - my_network
    logging:
      driver: "local"
      options:
        max-size: "10m"
        max-file: "3"
    env_file:
      - .env

  julia:
    container_name: julia_api
    build:
      context: julia_src/
      dockerfile: Dockerfile
    environment:
      - XPRESS_JL_SKIP_LIB_CHECK=True
      - XPRESS_INSTALLED=False
    command: julia --project=/opt/julia_src http.jl
    ports:
      - "8081:8081"
    volumes:
      - ./julia_src:/opt/julia_src
    networks:
      - my_network

networks:
  my_network:
