# Generated by Django 4.0.7 on 2023-09-26 16:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reoptjl', '0043_ghpinputs_installed_cost_wwhp_cooling_pump_per_ton_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ghpinputs',
            name='installed_cost_wwhp_cooling_pump_per_ton',
            field=models.FloatField(blank=True, default=700.0, help_text='Installed WWHP cooling heat pump cost in $/ton', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100000.0)]),
        ),
        migrations.AlterField(
            model_name='ghpinputs',
            name='installed_cost_wwhp_heating_pump_per_ton',
            field=models.FloatField(blank=True, default=700.0, help_text='Installed WWHP heating heat pump cost in $/ton', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100000.0)]),
        ),
    ]
