# Generated by Django 4.0.7 on 2024-09-16 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reoptjl', '0060_processheatloadinputs_addressable_load_fraction_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apimeta',
            name='reopt_version',
            field=models.TextField(blank=True, default='', help_text='Version number of the Julia package for REopt that is used to solve the problem.', null=True),
        ),
    ]
